package sy.model;



public class Stu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.age
     *
     * @mbggenerated Tue May 24 22:39:11 CST 2016
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.name
     *
     * @mbggenerated Tue May 24 22:39:11 CST 2016
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu.age
     *
     * @return the value of stu.age
     *
     * @mbggenerated Tue May 24 22:39:11 CST 2016
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu.age
     *
     * @param age the value for stu.age
     *
     * @mbggenerated Tue May 24 22:39:11 CST 2016
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu.name
     *
     * @return the value of stu.name
     *
     * @mbggenerated Tue May 24 22:39:11 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu.name
     *
     * @param name the value for stu.name
     *
     * @mbggenerated Tue May 24 22:39:11 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }
}